"""set is_calculated default false and update nulls

Revision ID: 7b3ccc7a543b
Revises: 8a448eb5e7db
Create Date: 2026-07-08 21:09:09.868446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3ccc7a543b'
down_revision: Union[str, Sequence[str], None] = '8a448eb5e7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'is_calculated', server_default='false')
    # Update existing NULL rows
    op.execute("UPDATE sections SET is_calculated = false WHERE is_calculated IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
