"""set sample_unit_count default and update nulls

Revision ID: 3463b67b5a39
Revises: d88bc47bac6e
Create Date: 2026-06-23 07:44:05.647298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3463b67b5a39'
down_revision: Union[str, Sequence[str], None] = 'd88bc47bac6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
     # Set server default for existing column
    op.alter_column('sections', 'sample_unit_count', server_default='0')
    # Update existing NULL rows to 0
    op.execute("UPDATE sections SET sample_unit_count = 0 WHERE sample_unit_count IS NULL;")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
