"""add is_calculated Column to Sections

Revision ID: 5489998452a1
Revises: ffb69497f8d3
Create Date: 2026-07-08 20:30:52.713526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5489998452a1'
down_revision: Union[str, Sequence[str], None] = 'ffb69497f8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('is_calculated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'is_calculated')
    # ### end Alembic commands ###
