"""add new column to detectionResult tble

Revision ID: ffb69497f8d3
Revises: a0aacdf70067
Create Date: 2026-07-07 11:16:40.845416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb69497f8d3'
down_revision: Union[str, Sequence[str], None] = 'a0aacdf70067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('severity_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_results', 'severity_label')
    # ### end Alembic commands ###
