"""add edited column to detection_result

Revision ID: d6320af07088
Revises: 4552d0fee3f7
Create Date: 2026-07-04 10:25:24.784019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6320af07088'
down_revision: Union[str, Sequence[str], None] = '4552d0fee3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_results', 'edited')
    # ### end Alembic commands ###
