"""add sample_unit_count column

Revision ID: d88bc47bac6e
Revises: c207fa5c4335
Create Date: 2026-06-23 07:37:32.301432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88bc47bac6e'
down_revision: Union[str, Sequence[str], None] = 'c207fa5c4335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('sample_unit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'sample_unit_count')
    # ### end Alembic commands ###
