"""New migration

Revision ID: c207fa5c4335
Revises: 10075f6385c2
Create Date: 2026-06-21 14:20:09.631199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c207fa5c4335'
down_revision: Union[str, Sequence[str], None] = '10075f6385c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('total_sections', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('network_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('chainage_start', sa.Float(), nullable=True),
    sa.Column('chainage_end', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('pixel_to_mm_factor', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pci_history',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('final_pci', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('deduct_values', sa.JSON(), nullable=True),
    sa.Column('cdv', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_units',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('is_random', sa.Boolean(), nullable=True),
    sa.Column('distress_inputs', sa.JSON(), nullable=True),
    sa.Column('gps_coords', sa.JSON(), nullable=True),
    sa.Column('pixel_to_mm_factor', sa.Float(), nullable=True),
    sa.Column('original_image', sa.String(), nullable=True),
    sa.Column('predicted_image', sa.String(), nullable=True),
    sa.Column('distress_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('pothole_depth', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_results',
    sa.Column('sample_unit_id', sa.UUID(), nullable=False),
    sa.Column('distress_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sample_unit_id'], ['sample_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_results')
    op.drop_table('sample_units')
    op.drop_table('pci_history')
    op.drop_table('sections')
    op.drop_table('networks')
    # ### end Alembic commands ###
