"""update network and section table to have start and end coordinates

Revision ID: 30a745506912
Revises: 7b3ccc7a543b
Create Date: 2026-07-11 19:22:20.965445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a745506912'
down_revision: Union[str, Sequence[str], None] = '7b3ccc7a543b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('start_coordinates', sa.JSON(), nullable=False))
    op.add_column('networks', sa.Column('end_coordinates', sa.JSON(), nullable=False))
    op.drop_column('networks', 'coordinates')
    op.add_column('sections', sa.Column('start_coordinates', sa.JSON(), nullable=False))
    op.add_column('sections', sa.Column('end_coordinates', sa.JSON(), nullable=False))
    op.drop_column('sections', 'chainage_start')
    op.drop_column('sections', 'coordinates')
    op.drop_column('sections', 'chainage_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('chainage_end', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('chainage_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sections', 'end_coordinates')
    op.drop_column('sections', 'start_coordinates')
    op.add_column('networks', sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('networks', 'end_coordinates')
    op.drop_column('networks', 'start_coordinates')
    # ### end Alembic commands ###
