"""add latest pci and rating to sections

Revision ID: a0aacdf70067
Revises: d6320af07088
Create Date: 2026-07-04 12:07:28.460452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aacdf70067'
down_revision: Union[str, Sequence[str], None] = 'd6320af07088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('latest_pci', sa.Float(), nullable=True))
    op.add_column('sections', sa.Column('latest_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'latest_rating')
    op.drop_column('sections', 'latest_pci')
    # ### end Alembic commands ###
